name: to
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hive_flutter: ^1.1.0
  go_router: ^14.6.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  intl: ^0.19.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  google_mlkit_smart_reply: ^0.4.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.2
  shimmer: ^3.0.0 # For skeleton loaders

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: 2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
